# --------------------------------------
# Hexo Butterfly Theme Configuration
# If you have any questions, please refer to the documentation
# Chinese: https://butterfly.js.org/
# English: https://butterfly.js.org/en/
# --------------------------------------

# --------------------------------------
# Navigation Settings
# --------------------------------------

nav:
  # Navigation bar logo image
  logo: /img/favicon.png
  display_title: true
  # Whether to fix navigation bar
  fixed: false

menu:
  首页: / || fas fa-home
  文章||fas fa-book:
    分类: /categories/ || fas fa-folder-open
    统计: /charts/ || fa fa-line-chart
    时间轴: /archives/ || fas fa-archive
  友链||fa-solid fa-user-group:
    本站友链: /link/ || fa-solid fa-user-tie
    随机开往: https://www.travellings.cn/go.html || fa fa-subway
    异次元之旅: https://travel.moe/go.html?travel=on || fa fa-taxi
    列表导航: https://zhblogs.ohyee.cc/ || fa fa-motorcycle
  关于: /about/ || fa fas fa-heart

# 友链样式，butterfly为默认样式，volantis为站点卡片样式,flexcard为弹性卡片样式,byer为粉丝彩蛋！
flink_style: flexcard # butterfly | volantis | flexcard | byer

# 统计功能
statistics:
  enable: true 