# 工作流名称
name: Deploy Hexo Blog # 部署 Hexo 博客

on:
  push:
    branches:
      - main # <<< 确保这里是你的 Hexo 源码仓库的主分支，可能是 main 或 master

jobs:
  build_and_deploy: # 构建并部署作业
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境下运行

    steps:
      - name: Checkout repository # 检出仓库
        uses: actions/checkout@v4
        with:
          submodules: false # 禁用子模块检查，如果你的主题是子模块且需要，请改为 true

      - name: Setup Node.js # 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20' # <<< 建议使用主要版本，例如 '20' 或 '22'，通常比精确版本号更稳定
          # cache: 'npm' # 可选：缓存依赖以加快构建速度
          # cache-dependency-path: 'package-lock.json' # 如果使用 package-lock.json

      - name: Install Dependencies # 安装依赖
        run: npm install # <<< 如果你使用 Yarn，则使用 yarn install。这个步骤会安装 package.json 中列出的所有依赖，包括 hexo 和 hexo-deployer-git

      # !!! 修复权限问题：给 hexo 可执行文件添加执行权限 !!!
      - name: Grant execute permission to hexo # 赋予 hexo 执行权限
        run: chmod +x ./node_modules/.bin/hexo # +x 表示添加执行权限

      - name: Clean and Generate Static Files # 清理并生成站点
        run: |
          # 使用 npx 来执行 hexo 命令，确保找到本地安装的 hexo 可执行文件
          npx hexo clean
          npx hexo generate

      # !!! 使用 peaceiris/actions-gh-pages Action 来部署 !!!
      # 这个 Action 会自动处理 Git 初始化、添加、提交和推送到目标仓库，并正确处理认证
      - name: Deploy to GitHub Pages # 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # 使用 peaceiris/actions-gh-pages Action，v3 是稳定版本

        with:
          # 部署需要的 GitHub Token，引用你在 Secrets 中添加的名称
          # Secret 的名称是 HEXO_DEPLOY，请确保你在仓库 Secrets 中添加的名称就是 HEXO_DEPLOY
          github_token: ${{ secrets.HEXO_DEPLOY }} # <<< 确保 Secret 名称正确 (HEXO_DEPLOY)

          # 要部署的目录，Hexo 生成的静态文件在 public 目录
          publish_dir: ./public # 发布目录

          # 部署的目标仓库，格式是 用户名/仓库名 (不能是 SSH 地址)
          publish_repo: wp-a/wp-a.github.io # <<< 替换为你的 GitHub 用户名，并确保仓库名正确

          # 部署到的分支，wp-a.github.io 这种用户/组织页通常部署到 main 分支
          publish_branch: main # <<< 通常是 main 或 master，取决于你的 wp-a.github.io 仓库设置

          # committer 和 author 信息，部署时会用这些信息创建 commit
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com

